  INFO root [0x00000e50] [2018-10-31 22:25:08,378] - 
  INFO root [0x00000e50] [2018-10-31 22:25:08,448] - -----------------------------------------------------------------------------------------


  INFO root [0x00000e50] [2018-10-31 22:25:09,834] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000e50] [2018-10-31 22:25:09,836] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000e50] [2018-10-31 22:25:09,836] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000e50] [2018-10-31 22:25:10,221] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00000e50] [2018-10-31 22:25:10,366] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00000e50] [2018-10-31 22:25:10,369] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:65307 )
  INFO root [0x00000e50] [2018-10-31 22:25:10,369] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:65307, SOMAXCONN=128.
  INFO root [0x00000e50] [2018-10-31 22:25:10,370] - server-configs:
  INFO root [0x00000e50] [2018-10-31 22:25:10,370] - 	gameUpdateHertz : 10
  INFO root [0x00000e50] [2018-10-31 22:25:10,370] - 	entryScriptFile : kbemain
  INFO root [0x00000e50] [2018-10-31 22:25:10,370] - 	internalAddr : 192.168.0.107:65307
  INFO root [0x00000e50] [2018-10-31 22:25:10,370] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00000e50] [2018-10-31 22:25:10,371] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00000e50] [2018-10-31 22:25:10,371] - 	componentID : 7001
  INFO root [0x00000e50] [2018-10-31 22:25:11,309] - Components::findLogger: found logger, addr:192.168.0.107:65285
  INFO root [0x00000e50] [2018-10-31 22:25:11,310] - Components::addComponent: reset orderLog, uid=29613!
  INFO root [0x00000e50] [2018-10-31 22:25:11,311] - Components::addComponent[logger], uid=29613, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000e50] [2018-10-31 22:25:11,634] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 29613. PID: 8684 ----
  INFO root [0x00000e50] [2018-10-31 22:25:11,634] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000e50] [2018-10-31 22:25:11,686] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000e50] [2018-10-31 22:25:11,747] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000e50] [2018-10-31 22:25:18,697] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000e50] [2018-10-31 22:25:18,822] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000e50] [2018-10-31 22:25:18,919] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000e50] [2018-10-31 22:25:20,748] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000e50] [2018-10-31 22:25:20,910] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000e50] [2018-10-31 22:25:20,960] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000e50] [2018-10-31 22:25:21,143] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000e50] [2018-10-31 22:25:21,773] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000e50] [2018-10-31 22:25:23,246] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000e50] [2018-10-31 22:25:23,247] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000e50] [2018-10-31 22:25:25,339] - loaded entity-script:Account(1).
 DEBUG root [0x00000e50] [2018-10-31 22:25:25,341] - loaded entity-script:CheckName(2).
 DEBUG root [0x00000e50] [2018-10-31 22:25:25,774] - loaded entity-script:Halls(3).
 DEBUG root [0x00000e50] [2018-10-31 22:25:25,826] - loaded entity-script:Room(4).
  INFO root [0x00000e50] [2018-10-31 22:25:25,827] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000e50] [2018-10-31 22:25:26,119] - TelnetServer server is running on port 40000
  INFO root [0x00000e50] [2018-10-31 22:25:26,811] - ---- baseapp is running ----
 DEBUG root [0x00000e50] [2018-10-31 22:25:26,863] - Components::process(): Request for the process of identity...
  WARN root [0x00000e50] [2018-10-31 22:25:33,400] - Forwarding logs to logger[192.168.0.107:65285/0/0/0]...
 ERROR root [0x00000e50] [2018-10-31 22:30:03,231] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000e50] [2018-10-31 22:30:03,235] - The following logs sent to logger failed:
  WARN root [0x00000e50] [2018-10-31 22:30:03,236] - ==> [2018-10-31 22:30:03 230] TCPPacketReceiver::processPendingEvents(192.168.0.107:65285): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000e50] [2018-10-31 22:30:03,236] - ==> [2018-10-31 22:30:03 231] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000e50] [2018-10-31 22:30:03,281] - TCPPacketReceiver::processPendingEvents(192.168.0.107:65288): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000e50] [2018-10-31 22:30:03,282] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000e50] [2018-10-31 22:30:03,299] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00000e50] [2018-10-31 22:30:03,300] - onBaseAppShutDown: state=0
  INFO root [0x00000e50] [2018-10-31 22:30:03,300] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00000e50] [2018-10-31 22:30:03,300] - onBaseAppShutDown: state=1
  INFO root [0x00000e50] [2018-10-31 22:30:03,300] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00000e50] [2018-10-31 22:30:03,300] - onBaseAppShutDown: state=2
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,420] - Halls::~Halls(): 2001
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,448] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000e50] [2018-10-31 22:30:03,449] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000027f8] [2018-10-31 22:30:04,547] - 
  INFO root [0x000027f8] [2018-10-31 22:30:04,548] - -----------------------------------------------------------------------------------------


  INFO root [0x000027f8] [2018-10-31 22:30:04,548] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000027f8] [2018-10-31 22:30:04,549] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000027f8] [2018-10-31 22:30:04,549] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000027f8] [2018-10-31 22:30:04,552] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x000027f8] [2018-10-31 22:30:04,552] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:65430 )
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:65430, SOMAXCONN=128.
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - server-configs:
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	gameUpdateHertz : 10
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	entryScriptFile : kbemain
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	internalAddr : 192.168.0.107:65430
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	externalCustomAddr : 127.0.0.1
  INFO root [0x000027f8] [2018-10-31 22:30:04,554] - 	componentID : 7001
  WARN root [0x000027f8] [2018-10-31 22:30:05,081] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20307, errorno=10048
  INFO root [0x000027f8] [2018-10-31 22:30:05,087] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 30694. PID: 11076 ----
  INFO root [0x000027f8] [2018-10-31 22:30:05,088] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000027f8] [2018-10-31 22:30:05,088] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000027f8] [2018-10-31 22:30:05,088] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,221] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,221] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,222] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,226] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,226] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,226] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,227] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,262] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000027f8] [2018-10-31 22:30:05,302] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000027f8] [2018-10-31 22:30:05,302] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,332] - loaded entity-script:Account(1).
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,333] - loaded entity-script:CheckName(2).
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,339] - loaded entity-script:Halls(3).
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,340] - loaded entity-script:Room(4).
  INFO root [0x000027f8] [2018-10-31 22:30:05,340] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000027f8] [2018-10-31 22:30:05,340] - TelnetServer server is running on port 40000
  INFO root [0x000027f8] [2018-10-31 22:30:05,631] - ---- baseapp is running ----
 DEBUG root [0x000027f8] [2018-10-31 22:30:05,631] - Components::process(): Request for the process of identity...
  WARN root [0x000027f8] [2018-10-31 22:30:11,711] - EntityApp::checkTickPeriod: tick took 6080% (6.08 seconds)!
  INFO root [0x000027f8] [2018-10-31 22:30:12,750] - Components::findComponents: find logger(1)...
  INFO root [0x000027f8] [2018-10-31 22:30:12,854] - Components::findComponents: found logger, addr:192.168.0.107:65427
  INFO root [0x000027f8] [2018-10-31 22:30:12,854] - Components::addComponent: reset orderLog, uid=30694!
  INFO root [0x000027f8] [2018-10-31 22:30:12,854] - Components::addComponent[logger], uid=30694, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027f8] [2018-10-31 22:30:12,856] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000027f8] [2018-10-31 22:30:12,959] - Components::findComponents: found dbmgr, addr:192.168.0.107:65429
  INFO root [0x000027f8] [2018-10-31 22:30:12,959] - Components::addComponent: reset orderLog, uid=30694!
  INFO root [0x000027f8] [2018-10-31 22:30:12,960] - Components::addComponent[dbmgr], uid=30694, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027f8] [2018-10-31 22:30:12,960] - Components::findComponents: found dbmgr, addr:192.168.0.107:65429
  WARN root [0x000027f8] [2018-10-31 22:30:13,961] - Forwarding logs to logger[192.168.0.107:65427/0/0/0]...
 ERROR root [0x000027f8] [2018-10-31 22:33:32,728] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000027f8] [2018-10-31 22:33:32,737] - The following logs sent to logger failed:
  WARN root [0x000027f8] [2018-10-31 22:33:32,737] - ==> [2018-10-31 22:33:32 728] TCPPacketReceiver::processPendingEvents(192.168.0.107:65427): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027f8] [2018-10-31 22:33:32,737] - ==> [2018-10-31 22:33:32 728] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000027f8] [2018-10-31 22:33:32,782] - TCPPacketReceiver::processPendingEvents(192.168.0.107:65429): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027f8] [2018-10-31 22:33:32,783] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000027f8] [2018-10-31 22:33:32,788] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000027f8] [2018-10-31 22:33:32,790] - onBaseAppShutDown: state=0
  INFO root [0x000027f8] [2018-10-31 22:33:32,790] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000027f8] [2018-10-31 22:33:32,790] - onBaseAppShutDown: state=1
  INFO root [0x000027f8] [2018-10-31 22:33:32,790] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000027f8] [2018-10-31 22:33:32,790] - onBaseAppShutDown: state=2
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,798] - Halls::~Halls(): 1
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,799] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000027f8] [2018-10-31 22:33:32,809] - Script::uninstall(): is successfully!
 DEBUG root [0x000027f8] [2018-10-31 22:33:32,809] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000021a8] [2018-10-31 22:33:34,025] - 
  INFO root [0x000021a8] [2018-10-31 22:33:34,026] - -----------------------------------------------------------------------------------------


  INFO root [0x000021a8] [2018-10-31 22:33:34,026] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000021a8] [2018-10-31 22:33:34,026] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000021a8] [2018-10-31 22:33:34,026] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000021a8] [2018-10-31 22:33:34,029] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x000021a8] [2018-10-31 22:33:34,029] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49176 )
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49176, SOMAXCONN=128.
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - server-configs:
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - 	gameUpdateHertz : 10
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - 	entryScriptFile : kbemain
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - 	internalAddr : 192.168.0.107:49176
  INFO root [0x000021a8] [2018-10-31 22:33:34,030] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x000021a8] [2018-10-31 22:33:34,031] - 	externalCustomAddr : c.55908.3m.dkys.org
  INFO root [0x000021a8] [2018-10-31 22:33:34,031] - 	componentID : 7001
  INFO root [0x000021a8] [2018-10-31 22:33:35,712] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 31377. PID: 9956 ----
  INFO root [0x000021a8] [2018-10-31 22:33:35,713] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000021a8] [2018-10-31 22:33:35,713] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000021a8] [2018-10-31 22:33:35,713] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,843] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,843] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,844] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,848] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,849] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,849] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,850] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,888] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000021a8] [2018-10-31 22:33:35,924] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000021a8] [2018-10-31 22:33:35,925] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,955] - loaded entity-script:Account(1).
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,956] - loaded entity-script:CheckName(2).
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,961] - loaded entity-script:Halls(3).
 DEBUG root [0x000021a8] [2018-10-31 22:33:35,962] - loaded entity-script:Room(4).
  INFO root [0x000021a8] [2018-10-31 22:33:35,962] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000021a8] [2018-10-31 22:33:35,963] - TelnetServer server is running on port 40000
  INFO root [0x000021a8] [2018-10-31 22:33:36,307] - ---- baseapp is running ----
 DEBUG root [0x000021a8] [2018-10-31 22:33:36,308] - Components::process(): Request for the process of identity...
  WARN root [0x000021a8] [2018-10-31 22:33:42,401] - EntityApp::checkTickPeriod: tick took 6094% (6.09 seconds)!
  INFO root [0x000021a8] [2018-10-31 22:33:43,427] - Components::findComponents: find logger(1)...
  INFO root [0x000021a8] [2018-10-31 22:33:43,530] - Components::findComponents: found logger, addr:192.168.0.107:49178
  INFO root [0x000021a8] [2018-10-31 22:33:43,530] - Components::addComponent: reset orderLog, uid=31377!
  INFO root [0x000021a8] [2018-10-31 22:33:43,531] - Components::addComponent[logger], uid=31377, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000021a8] [2018-10-31 22:33:43,533] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000021a8] [2018-10-31 22:33:43,639] - Components::findComponents: found dbmgr, addr:192.168.0.107:49171
  INFO root [0x000021a8] [2018-10-31 22:33:43,639] - Components::addComponent: reset orderLog, uid=31377!
  INFO root [0x000021a8] [2018-10-31 22:33:43,640] - Components::addComponent[dbmgr], uid=31377, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000021a8] [2018-10-31 22:33:43,640] - Components::findComponents: found dbmgr, addr:192.168.0.107:49171
  WARN root [0x000021a8] [2018-10-31 22:33:44,641] - Forwarding logs to logger[192.168.0.107:49178/0/0/0]...
 ERROR root [0x000021a8] [2018-10-31 22:58:35,850] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000021a8] [2018-10-31 22:58:35,861] - The following logs sent to logger failed:
  WARN root [0x000021a8] [2018-10-31 22:58:35,861] - ==> [2018-10-31 22:58:35 847] TCPPacketReceiver::processPendingEvents(192.168.0.107:49178): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021a8] [2018-10-31 22:58:35,861] - ==> [2018-10-31 22:58:35 850] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000021a8] [2018-10-31 22:58:35,916] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49171): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021a8] [2018-10-31 22:58:35,918] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000021a8] [2018-10-31 22:58:35,931] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000021a8] [2018-10-31 22:58:35,936] - onBaseAppShutDown: state=0
  INFO root [0x000021a8] [2018-10-31 22:58:35,936] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000021a8] [2018-10-31 22:58:35,937] - onBaseAppShutDown: state=1
  INFO root [0x000021a8] [2018-10-31 22:58:35,937] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000021a8] [2018-10-31 22:58:35,937] - onBaseAppShutDown: state=2
 ERROR root [0x000021a8] [2018-10-31 22:58:35,945] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000021a8] [2018-10-31 22:58:35,948] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,948] - Account::~Account(): 2002
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,967] - Halls::~Halls(): 2001
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,968] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,969] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,969] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000021a8] [2018-10-31 22:58:35,979] - Script::uninstall(): is successfully!
 DEBUG root [0x000021a8] [2018-10-31 22:58:35,979] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000031c8] [2018-10-31 23:03:36,331] - 
  INFO root [0x000031c8] [2018-10-31 23:03:36,331] - -----------------------------------------------------------------------------------------


  INFO root [0x000031c8] [2018-10-31 23:03:36,332] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000031c8] [2018-10-31 23:03:36,332] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000031c8] [2018-10-31 23:03:36,332] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000031c8] [2018-10-31 23:03:36,345] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x000031c8] [2018-10-31 23:03:36,345] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x000031c8] [2018-10-31 23:03:36,347] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50010 )
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50010, SOMAXCONN=128.
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - server-configs:
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	gameUpdateHertz : 10
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	entryScriptFile : kbemain
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	internalAddr : 192.168.0.107:50010
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	externalCustomAddr : 171.88.53.16
  INFO root [0x000031c8] [2018-10-31 23:03:36,348] - 	componentID : 7001
  INFO root [0x000031c8] [2018-10-31 23:03:36,744] - Components::findLogger: found logger, addr:192.168.0.107:50004
  INFO root [0x000031c8] [2018-10-31 23:03:36,745] - Components::addComponent: reset orderLog, uid=4493!
  INFO root [0x000031c8] [2018-10-31 23:03:36,745] - Components::addComponent[logger], uid=4493, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000031c8] [2018-10-31 23:03:36,749] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 4493. PID: 12988 ----
  INFO root [0x000031c8] [2018-10-31 23:03:36,749] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000031c8] [2018-10-31 23:03:36,750] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000031c8] [2018-10-31 23:03:36,750] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,879] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,880] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,880] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,884] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,884] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,884] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,884] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,917] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000031c8] [2018-10-31 23:03:36,953] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000031c8] [2018-10-31 23:03:36,953] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,974] - loaded entity-script:Account(1).
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,976] - loaded entity-script:CheckName(2).
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,982] - loaded entity-script:Halls(3).
 DEBUG root [0x000031c8] [2018-10-31 23:03:36,983] - loaded entity-script:Room(4).
  INFO root [0x000031c8] [2018-10-31 23:03:36,983] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000031c8] [2018-10-31 23:03:36,984] - TelnetServer server is running on port 40000
  INFO root [0x000031c8] [2018-10-31 23:03:37,316] - ---- baseapp is running ----
 DEBUG root [0x000031c8] [2018-10-31 23:03:37,316] - Components::process(): Request for the process of identity...
  WARN root [0x000031c8] [2018-10-31 23:03:43,386] - Forwarding logs to logger[192.168.0.107:50004/0/0/0]...
 ERROR root [0x000031c8] [2018-10-31 23:09:45,793] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000031c8] [2018-10-31 23:09:45,806] - The following logs sent to logger failed:
  WARN root [0x000031c8] [2018-10-31 23:09:45,806] - ==> [2018-10-31 23:09:45 786] TCPPacketReceiver::processPendingEvents(192.168.0.107:50004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000031c8] [2018-10-31 23:09:45,806] - ==> [2018-10-31 23:09:45 795] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000031c8] [2018-10-31 23:09:45,807] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50005): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000031c8] [2018-10-31 23:09:45,808] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000031c8] [2018-10-31 23:09:45,811] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000031c8] [2018-10-31 23:09:45,812] - onBaseAppShutDown: state=0
  INFO root [0x000031c8] [2018-10-31 23:09:45,812] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000031c8] [2018-10-31 23:09:45,813] - onBaseAppShutDown: state=1
  INFO root [0x000031c8] [2018-10-31 23:09:45,813] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000031c8] [2018-10-31 23:09:45,813] - onBaseAppShutDown: state=2
  WARN root [0x000031c8] [2018-10-31 23:09:45,813] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50008): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000031c8] [2018-10-31 23:09:45,813] - Components::removeComponentByChannel: baseappmgr : 5000, Normal exit!
  WARN root [0x000031c8] [2018-10-31 23:09:45,813] - ServerApp::shutDown:  In shuttingdown!
  WARN root [0x000031c8] [2018-10-31 23:09:45,814] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50007): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000031c8] [2018-10-31 23:09:45,814] - Components::removeComponentByChannel: cellappmgr : 6000, Normal exit!
  WARN root [0x000031c8] [2018-10-31 23:09:45,815] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50006): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000031c8] [2018-10-31 23:09:45,815] - Components::removeComponentByChannel: cellapp : 8001, Normal exit!
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,827] - Halls::~Halls(): 1
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,828] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,828] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,828] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,829] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,829] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,829] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,829] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,829] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000031c8] [2018-10-31 23:09:45,844] - Script::uninstall(): is successfully!
 DEBUG root [0x000031c8] [2018-10-31 23:09:45,844] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000031c8] [2018-10-31 23:09:46,144] - ThreadPool::destroy(): waiting for thread(2)[0x5be508,0x5be4a0,], try=1
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - TPThread::~TPThread(): 0x5be508
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - TPThread::~TPThread(): 0x5be4a0
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - ThreadPool::destroy(): successfully!
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - Bundle::destroyObjPool(): size 2.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - Channel::destroyObjPool(): size 16.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - TCPPacket::destroyObjPool(): size 1.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,544] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,545] - EndPoint::destroyObjPool(): size 16.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,545] - Address::destroyObjPool(): size 0.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,545] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x000031c8] [2018-10-31 23:09:46,545] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x000031c8] [2018-10-31 23:09:46,545] - baseapp(7001) has shut down.
  INFO root [0x000031c8] [2018-10-31 23:09:47,545] - EventDispatcher()::~EventDispatcher: Num timers = 2
