  INFO root [2018-11-03 13:43:57,652] - 
  INFO root [2018-11-03 13:43:57,699] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 13:43:58,444] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 13:43:58,445] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 13:43:58,446] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 13:43:58,740] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 13:43:58,859] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 13:43:58,864] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54384 )
  INFO root [2018-11-03 13:43:58,865] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54384, SOMAXCONN=128.
  INFO root [2018-11-03 13:43:58,866] - server-configs:
  INFO root [2018-11-03 13:43:58,866] - 	internalAddr : 192.168.0.107:54384
  INFO root [2018-11-03 13:43:58,867] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 13:43:58,867] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-11-03 13:43:58,868] - 	componentID : 9000
  INFO root [2018-11-03 13:43:59,635] - Components::findLogger: found logger, addr:192.168.0.107:54377
  INFO root [2018-11-03 13:43:59,636] - Components::addComponent: reset orderLog, uid=20302!
  INFO root [2018-11-03 13:43:59,636] - Components::addComponent[logger], uid=20302, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 13:43:59,763] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20302. PID: 2796 ----
  INFO root [2018-11-03 13:43:59,764] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 13:43:59,803] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 13:43:59,913] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 13:44:07,425] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 13:44:07,630] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 13:44:07,658] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 13:44:08,534] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 13:44:08,636] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 13:44:08,766] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 13:44:08,936] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 13:44:09,929] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 13:44:12,251] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 13:44:12,252] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 13:44:12,440] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 13:44:12,441] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 13:44:12,972] - ---- loginapp is running ----
 DEBUG root [2018-11-03 13:44:12,973] - Components::process(): Request for the process of identity...
  WARN root [2018-11-03 13:44:19,735] - Forwarding logs to logger[192.168.0.107:54377/0/0/0]...
 ERROR root [2018-11-03 13:46:20,345] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 13:46:20,368] - The following logs sent to logger failed:
  WARN root [2018-11-03 13:46:20,368] - ==> [2018-11-03 13:46:20 340] TCPPacketReceiver::processPendingEvents(192.168.0.107:54377): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 13:46:20,368] - ==> [2018-11-03 13:46:20 346] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-11-03 13:46:20,417] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54381): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 13:46:20,422] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 13:46:20,442] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-11-03 13:46:20,446] - onLoginAppShutDown()
  INFO root [2018-11-03 13:46:20,446] - Shutdowner::onShutdown: shutting down
  INFO root [2018-11-03 13:46:20,446] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-11-03 13:46:20,446] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 13:46:20,447] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 13:46:20,515] - Script::uninstall(): is successfully!
 DEBUG root [2018-11-03 13:46:20,515] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-11-03 13:46:21,868] - 
  INFO root [2018-11-03 13:46:21,869] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 13:46:21,869] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 13:46:21,869] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 13:46:21,870] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 13:46:21,877] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 13:46:21,877] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 13:46:21,879] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54447 )
  INFO root [2018-11-03 13:46:21,879] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54447, SOMAXCONN=128.
  INFO root [2018-11-03 13:46:21,879] - server-configs:
  INFO root [2018-11-03 13:46:21,879] - 	internalAddr : 192.168.0.107:54447
  INFO root [2018-11-03 13:46:21,879] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 13:46:21,879] - 	externalCustomAddr : c.55908.3m.dkys.org
  INFO root [2018-11-03 13:46:21,879] - 	componentID : 9000
  INFO root [2018-11-03 13:46:23,556] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20854. PID: 10164 ----
  INFO root [2018-11-03 13:46:23,556] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 13:46:23,557] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 13:46:23,557] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 13:46:23,679] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 13:46:23,680] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 13:46:23,680] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 13:46:23,683] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 13:46:23,683] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 13:46:23,683] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 13:46:23,684] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 13:46:23,714] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 13:46:23,751] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 13:46:23,751] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 13:46:23,754] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 13:46:23,754] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 13:46:24,100] - ---- loginapp is running ----
 DEBUG root [2018-11-03 13:46:24,101] - Components::process(): Request for the process of identity...
  INFO root [2018-11-03 13:46:31,175] - Components::findComponents: find logger(1)...
  INFO root [2018-11-03 13:46:31,263] - Components::findComponents: found logger, addr:192.168.0.107:54451
  INFO root [2018-11-03 13:46:31,263] - Components::addComponent: reset orderLog, uid=20854!
  INFO root [2018-11-03 13:46:31,264] - Components::addComponent[logger], uid=20854, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 13:46:31,265] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-11-03 13:46:31,367] - Components::findComponents: found dbmgr, addr:192.168.0.107:54448
  INFO root [2018-11-03 13:46:31,368] - Components::addComponent: reset orderLog, uid=20854!
  INFO root [2018-11-03 13:46:31,368] - Components::addComponent[dbmgr], uid=20854, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 13:46:31,368] - Components::findComponents: found dbmgr, addr:192.168.0.107:54448
  WARN root [2018-11-03 13:46:32,369] - Forwarding logs to logger[192.168.0.107:54451/0/0/0]...
 ERROR root [2018-11-03 14:09:52,773] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:09:52,797] - The following logs sent to logger failed:
  WARN root [2018-11-03 14:09:52,798] - ==> [2018-11-03 14:09:52 769] TCPPacketReceiver::processPendingEvents(192.168.0.107:54451): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:09:52,798] - ==> [2018-11-03 14:09:52 773] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-11-03 14:09:52,854] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54448): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:09:52,856] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:09:52,872] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-11-03 14:09:52,872] - onLoginAppShutDown()
  INFO root [2018-11-03 14:09:52,872] - Shutdowner::onShutdown: shutting down
  INFO root [2018-11-03 14:09:52,872] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:09:52,873] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:09:52,882] - Script::uninstall(): is successfully!
 DEBUG root [2018-11-03 14:09:52,882] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-11-03 14:09:53,182] - ThreadPool::destroy(): waiting for thread(2)[0x173a590,0x173a528,], try=1
  INFO root [2018-11-03 14:09:54,165] - 
  INFO root [2018-11-03 14:09:54,165] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 14:09:54,166] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 14:09:54,166] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 14:09:54,166] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 14:09:54,173] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 14:09:54,173] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 14:09:54,174] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54984 )
  INFO root [2018-11-03 14:09:54,174] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54984, SOMAXCONN=128.
  INFO root [2018-11-03 14:09:54,174] - server-configs:
  INFO root [2018-11-03 14:09:54,174] - 	internalAddr : 192.168.0.107:54984
  INFO root [2018-11-03 14:09:54,174] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 14:09:54,175] - 	externalCustomAddr : 22577mw996.iask.in
  INFO root [2018-11-03 14:09:54,175] - 	componentID : 9000
  INFO root [2018-11-03 14:09:55,899] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 25465. PID: 4564 ----
  INFO root [2018-11-03 14:09:55,900] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 14:09:55,900] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 14:09:55,900] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 14:09:56,023] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:09:56,024] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:09:56,024] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:09:56,027] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:09:56,027] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:09:56,027] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:09:56,028] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:09:56,060] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:09:56,092] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 14:09:56,092] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 14:09:56,094] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 14:09:56,094] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 14:09:56,394] - ---- loginapp is running ----
 DEBUG root [2018-11-03 14:09:56,395] - Components::process(): Request for the process of identity...
  INFO root [2018-11-03 14:10:03,516] - Components::findComponents: find logger(1)...
  INFO root [2018-11-03 14:10:03,620] - Components::findComponents: found logger, addr:192.168.0.107:54987
  INFO root [2018-11-03 14:10:03,621] - Components::addComponent: reset orderLog, uid=25465!
  INFO root [2018-11-03 14:10:03,621] - Components::addComponent[logger], uid=25465, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:10:03,622] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-11-03 14:10:03,727] - Components::findComponents: found dbmgr, addr:192.168.0.107:54986
  INFO root [2018-11-03 14:10:03,727] - Components::addComponent: reset orderLog, uid=25465!
  INFO root [2018-11-03 14:10:03,728] - Components::addComponent[dbmgr], uid=25465, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:10:03,728] - Components::findComponents: found dbmgr, addr:192.168.0.107:54986
  WARN root [2018-11-03 14:10:04,729] - Forwarding logs to logger[192.168.0.107:54987/0/0/0]...
 ERROR root [2018-11-03 14:11:38,031] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:11:38,052] - The following logs sent to logger failed:
  WARN root [2018-11-03 14:11:38,052] - ==> [2018-11-03 14:11:38 026] TCPPacketReceiver::processPendingEvents(192.168.0.107:54987): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:11:38,052] - ==> [2018-11-03 14:11:38 031] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-11-03 14:11:38,102] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54986): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:11:38,107] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:11:38,125] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-11-03 14:11:38,125] - onLoginAppShutDown()
  INFO root [2018-11-03 14:11:38,125] - Shutdowner::onShutdown: shutting down
  INFO root [2018-11-03 14:11:38,126] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:11:38,126] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:11:38,135] - Script::uninstall(): is successfully!
 DEBUG root [2018-11-03 14:11:38,136] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-11-03 14:11:38,436] - ThreadPool::destroy(): waiting for thread(2)[0x40bca8,0x40bc40,], try=1
  INFO root [2018-11-03 14:11:39,433] - 
  INFO root [2018-11-03 14:11:39,440] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 14:11:39,441] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 14:11:39,441] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 14:11:39,441] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 14:11:39,446] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 14:11:39,446] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 14:11:39,449] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55050 )
  INFO root [2018-11-03 14:11:39,449] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55050, SOMAXCONN=128.
  INFO root [2018-11-03 14:11:39,449] - server-configs:
  INFO root [2018-11-03 14:11:39,450] - 	internalAddr : 192.168.0.107:55050
  INFO root [2018-11-03 14:11:39,450] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 14:11:39,450] - 	externalCustomAddr : c.55908.3m.dkys.org
  INFO root [2018-11-03 14:11:39,450] - 	componentID : 9000
  INFO root [2018-11-03 14:11:41,164] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 25808. PID: 4520 ----
  INFO root [2018-11-03 14:11:41,165] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 14:11:41,165] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 14:11:41,165] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 14:11:41,288] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:11:41,288] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:11:41,289] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:11:41,292] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:11:41,292] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:11:41,292] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:11:41,293] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:11:41,322] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:11:41,353] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 14:11:41,354] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 14:11:41,356] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 14:11:41,356] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 14:11:41,649] - ---- loginapp is running ----
 DEBUG root [2018-11-03 14:11:41,650] - Components::process(): Request for the process of identity...
  INFO root [2018-11-03 14:11:48,717] - Components::findComponents: find logger(1)...
  INFO root [2018-11-03 14:11:48,753] - Components::findComponents: found logger, addr:192.168.0.107:55051
  INFO root [2018-11-03 14:11:48,754] - Components::addComponent: reset orderLog, uid=25808!
  INFO root [2018-11-03 14:11:48,754] - Components::addComponent[logger], uid=25808, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:11:48,755] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-11-03 14:11:48,861] - Components::findComponents: found dbmgr, addr:192.168.0.107:55047
  INFO root [2018-11-03 14:11:48,862] - Components::addComponent: reset orderLog, uid=25808!
  INFO root [2018-11-03 14:11:48,862] - Components::addComponent[dbmgr], uid=25808, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:11:48,864] - Components::findComponents: found dbmgr, addr:192.168.0.107:55047
  WARN root [2018-11-03 14:11:49,865] - Forwarding logs to logger[192.168.0.107:55051/0/0/0]...
 ERROR root [2018-11-03 14:13:23,521] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:13:23,545] - The following logs sent to logger failed:
  WARN root [2018-11-03 14:13:23,545] - ==> [2018-11-03 14:13:23 516] TCPPacketReceiver::processPendingEvents(192.168.0.107:55051): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:13:23,545] - ==> [2018-11-03 14:13:23 522] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-11-03 14:13:23,594] - TCPPacketReceiver::processPendingEvents(192.168.0.107:55047): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-11-03 14:13:23,599] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-11-03 14:13:23,616] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-11-03 14:13:23,616] - onLoginAppShutDown()
  INFO root [2018-11-03 14:13:23,617] - Shutdowner::onShutdown: shutting down
  INFO root [2018-11-03 14:13:23,617] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:13:23,617] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:13:23,618] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:13:23,627] - Script::uninstall(): is successfully!
 DEBUG root [2018-11-03 14:13:23,627] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-11-03 14:13:23,927] - ThreadPool::destroy(): waiting for thread(2)[0x1a9a590,0x1a9a528,], try=1
  INFO root [2018-11-03 14:14:16,803] - 
  INFO root [2018-11-03 14:14:16,804] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 14:14:16,804] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 14:14:16,805] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 14:14:16,805] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 14:14:16,808] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 14:14:16,808] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 14:14:16,809] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55125 )
  INFO root [2018-11-03 14:14:16,809] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55125, SOMAXCONN=128.
  INFO root [2018-11-03 14:14:16,810] - server-configs:
  INFO root [2018-11-03 14:14:16,810] - 	internalAddr : 192.168.0.107:55125
  INFO root [2018-11-03 14:14:16,810] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 14:14:16,810] - 	externalCustomAddr : c.55908.3m.dkys.org
  INFO root [2018-11-03 14:14:16,810] - 	componentID : 9000
  INFO root [2018-11-03 14:14:18,523] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26324. PID: 8364 ----
  INFO root [2018-11-03 14:14:18,524] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 14:14:18,524] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 14:14:18,524] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 14:14:18,648] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:14:18,648] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:14:18,649] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:14:18,652] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:14:18,652] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:14:18,652] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:14:18,652] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:14:18,680] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:14:18,713] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 14:14:18,713] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 14:14:18,715] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 14:14:18,715] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 14:14:19,015] - ---- loginapp is running ----
 DEBUG root [2018-11-03 14:14:19,015] - Components::process(): Request for the process of identity...
  INFO root [2018-11-03 14:14:26,097] - Components::findComponents: find logger(1)...
 ERROR root [2018-11-03 14:14:27,625] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:27,627] - Components::findComponents: receive error!
  WARN root [2018-11-03 14:14:27,628] - Components::findComponents: not found logger!
  INFO root [2018-11-03 14:14:28,636] - Components::findComponents: find dbmgr(1)...
 ERROR root [2018-11-03 14:14:30,138] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:30,141] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:31,156] - Components::findComponents: find dbmgr(2)...
 ERROR root [2018-11-03 14:14:32,658] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:32,659] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:33,676] - Components::findComponents: find dbmgr(3)...
 ERROR root [2018-11-03 14:14:35,178] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:35,180] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:36,196] - Components::findComponents: find dbmgr(4)...
 ERROR root [2018-11-03 14:14:37,698] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:37,701] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:38,706] - Components::findComponents: find dbmgr(5)...
 ERROR root [2018-11-03 14:14:40,208] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:40,211] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:41,216] - Components::findComponents: find dbmgr(6)...
 ERROR root [2018-11-03 14:14:42,719] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:42,722] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:43,736] - Components::findComponents: find dbmgr(7)...
 ERROR root [2018-11-03 14:14:45,238] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:45,242] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:46,256] - Components::findComponents: find dbmgr(8)...
 ERROR root [2018-11-03 14:14:47,757] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:47,758] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:48,776] - Components::findComponents: find dbmgr(9)...
 ERROR root [2018-11-03 14:14:50,278] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:50,281] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:51,296] - Components::findComponents: find dbmgr(10)...
 ERROR root [2018-11-03 14:14:52,798] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:52,800] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:53,806] - Components::findComponents: find dbmgr(11)...
 ERROR root [2018-11-03 14:14:55,308] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:55,308] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:56,316] - Components::findComponents: find dbmgr(12)...
 ERROR root [2018-11-03 14:14:57,818] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:14:57,820] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:14:58,835] - Components::findComponents: find dbmgr(13)...
 ERROR root [2018-11-03 14:15:00,337] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-11-03 14:15:00,339] - Components::findComponents: receive error!
  INFO root [2018-11-03 14:15:01,742] - 
  INFO root [2018-11-03 14:15:01,743] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-03 14:15:01,744] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-03 14:15:01,744] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-03 14:15:01,744] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-03 14:15:01,748] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-11-03 14:15:01,748] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-11-03 14:15:01,750] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55144 )
  INFO root [2018-11-03 14:15:01,750] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55144, SOMAXCONN=128.
  INFO root [2018-11-03 14:15:01,750] - server-configs:
  INFO root [2018-11-03 14:15:01,750] - 	internalAddr : 192.168.0.107:55144
  INFO root [2018-11-03 14:15:01,750] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-11-03 14:15:01,750] - 	externalCustomAddr : c.55908.3m.dkys.org
  INFO root [2018-11-03 14:15:01,750] - 	componentID : 9000
  INFO root [2018-11-03 14:15:03,465] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26471. PID: 9976 ----
  INFO root [2018-11-03 14:15:03,465] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-03 14:15:03,466] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-03 14:15:03,466] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-03 14:15:03,595] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-03 14:15:03,595] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-03 14:15:03,596] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-03 14:15:03,598] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-03 14:15:03,599] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-03 14:15:03,599] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-03 14:15:03,600] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-03 14:15:03,641] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-03 14:15:03,682] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-03 14:15:03,682] - Script::install(): KBExtra is successfully!
S_INFO root [2018-11-03 14:15:03,685] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-03 14:15:03,685] - TelnetServer server is running on port 31000
  INFO root [2018-11-03 14:15:04,020] - ---- loginapp is running ----
 DEBUG root [2018-11-03 14:15:04,021] - Components::process(): Request for the process of identity...
  INFO root [2018-11-03 14:15:11,145] - Components::findComponents: find logger(1)...
  WARN root [2018-11-03 14:15:11,456] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20865, errorno=10048
  INFO root [2018-11-03 14:15:12,465] - Components::findComponents: find logger(2)...
  INFO root [2018-11-03 14:15:12,561] - Components::findComponents: found logger, addr:192.168.0.107:55142
  INFO root [2018-11-03 14:15:12,562] - Components::addComponent: reset orderLog, uid=26471!
  INFO root [2018-11-03 14:15:12,562] - Components::addComponent[logger], uid=26471, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:15:12,565] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-11-03 14:15:12,663] - Components::findComponents: found dbmgr, addr:192.168.0.107:55139
  INFO root [2018-11-03 14:15:12,664] - Components::addComponent: reset orderLog, uid=26471!
  INFO root [2018-11-03 14:15:12,664] - Components::addComponent[dbmgr], uid=26471, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-03 14:15:12,664] - Components::findComponents: found dbmgr, addr:192.168.0.107:55139
  WARN root [2018-11-03 14:15:13,664] - Forwarding logs to logger[192.168.0.107:55142/0/0/0]...
