  INFO root [2018-10-30 00:39:13,346] - 
  INFO root [2018-10-30 00:39:13,391] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 00:39:16,902] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 00:39:16,904] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 00:39:16,905] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 00:39:21,580] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 00:39:21,633] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 00:39:21,639] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49587 )
  INFO root [2018-10-30 00:39:21,639] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49587, SOMAXCONN=128.
  INFO root [2018-10-30 00:39:21,640] - server-configs:
  INFO root [2018-10-30 00:39:21,640] - 	internalAddr : 192.168.0.107:49587
  INFO root [2018-10-30 00:39:21,640] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 00:39:21,641] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 00:39:21,641] - 	componentID : 9000
  INFO root [2018-10-30 00:39:22,421] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 15852. PID: 5004 ----
  INFO root [2018-10-30 00:39:22,422] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 00:39:22,423] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 00:39:22,459] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 00:39:34,332] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:39:34,404] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:39:34,499] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:39:36,300] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:39:36,535] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:39:36,581] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:39:36,624] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:39:37,429] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:39:39,650] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 00:39:39,652] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 00:39:40,064] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 00:39:40,065] - TelnetServer server is running on port 31000
  WARN root [2018-10-30 00:39:40,067] - e:\kbengine\kbe\src\server\loginapp\loginapp.cpp:153: Profile scriptCall took 0.15 seconds
  INFO root [2018-10-30 00:39:40,755] - ---- loginapp is running ----
 DEBUG root [2018-10-30 00:39:40,792] - Components::process(): Request for the process of identity...
  WARN root [2018-10-30 00:39:47,678] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.29 seconds
  INFO root [2018-10-30 00:39:48,699] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 00:39:48,730] - Components::findComponents: found logger, addr:192.168.0.107:49370
  INFO root [2018-10-30 00:39:48,731] - Components::addComponent: reset orderLog, uid=15852!
  INFO root [2018-10-30 00:39:48,732] - Components::addComponent[logger], uid=15852, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:39:48,764] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-10-30 00:39:49,836] - Forwarding logs to logger[192.168.0.107:49370/0/0/0]...
  INFO root [2018-10-30 00:41:01,656] - 
  INFO root [2018-10-30 00:41:01,657] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 00:41:01,657] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 00:41:01,658] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 00:41:01,658] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 00:41:01,660] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 00:41:01,660] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 00:41:01,661] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49614 )
  INFO root [2018-10-30 00:41:01,662] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49614, SOMAXCONN=128.
  INFO root [2018-10-30 00:41:01,662] - server-configs:
  INFO root [2018-10-30 00:41:01,662] - 	internalAddr : 192.168.0.107:49614
  INFO root [2018-10-30 00:41:01,662] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 00:41:01,662] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 00:41:01,662] - 	componentID : 9000
  INFO root [2018-10-30 00:41:03,350] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 16348. PID: 6300 ----
  INFO root [2018-10-30 00:41:03,351] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 00:41:03,351] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 00:41:03,351] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 00:41:03,473] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:41:03,474] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:41:03,474] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:41:03,477] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:41:03,477] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:41:03,477] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:41:03,478] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:41:03,504] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:41:03,531] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 00:41:03,531] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 00:41:03,533] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 00:41:03,533] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 00:41:03,814] - ---- loginapp is running ----
 DEBUG root [2018-10-30 00:41:03,814] - Components::process(): Request for the process of identity...
  WARN root [2018-10-30 00:41:04,125] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20965, errorno=10048
  INFO root [2018-10-30 00:41:11,253] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 00:41:11,341] - Components::findComponents: found logger, addr:192.168.0.107:49610
  INFO root [2018-10-30 00:41:11,342] - Components::addComponent: reset orderLog, uid=16348!
  INFO root [2018-10-30 00:41:11,343] - Components::addComponent[logger], uid=16348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:41:11,345] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-10-30 00:41:12,444] - Forwarding logs to logger[192.168.0.107:49610/0/0/0]...
  INFO root [2018-10-30 00:43:12,397] - 
  INFO root [2018-10-30 00:43:12,397] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 00:43:12,397] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 00:43:12,398] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 00:43:12,398] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 00:43:12,403] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 00:43:12,403] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 00:43:12,405] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49655 )
  INFO root [2018-10-30 00:43:12,405] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49655, SOMAXCONN=128.
  INFO root [2018-10-30 00:43:12,405] - server-configs:
  INFO root [2018-10-30 00:43:12,405] - 	internalAddr : 192.168.0.107:49655
  INFO root [2018-10-30 00:43:12,406] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 00:43:12,406] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 00:43:12,406] - 	componentID : 9000
  WARN root [2018-10-30 00:43:12,913] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20287, errorno=10048
  INFO root [2018-10-30 00:43:12,919] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 16776. PID: 6380 ----
  INFO root [2018-10-30 00:43:12,919] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 00:43:12,920] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 00:43:12,920] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 00:43:13,043] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:43:13,043] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:43:13,044] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:43:13,047] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:43:13,047] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:43:13,047] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:43:13,047] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:43:13,074] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:43:13,102] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 00:43:13,102] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 00:43:13,104] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 00:43:13,104] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 00:43:13,420] - ---- loginapp is running ----
 DEBUG root [2018-10-30 00:43:13,420] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 00:43:20,486] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 00:43:20,516] - Components::findComponents: found logger, addr:192.168.0.107:49653
  INFO root [2018-10-30 00:43:20,516] - Components::addComponent: reset orderLog, uid=16776!
  INFO root [2018-10-30 00:43:20,517] - Components::addComponent[logger], uid=16776, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:43:20,519] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 00:43:20,619] - Components::findComponents: found dbmgr, addr:192.168.0.107:49658
  INFO root [2018-10-30 00:43:20,620] - Components::addComponent: reset orderLog, uid=16776!
  INFO root [2018-10-30 00:43:20,620] - Components::addComponent[dbmgr], uid=16776, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:43:20,620] - Components::findComponents: found dbmgr, addr:192.168.0.107:49658
  WARN root [2018-10-30 00:43:21,621] - Forwarding logs to logger[192.168.0.107:49653/0/0/0]...
 ERROR root [2018-10-30 00:48:33,380] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 00:48:33,385] - The following logs sent to logger failed:
  WARN root [2018-10-30 00:48:33,385] - ==> [2018-10-30 00:48:33 380] TCPPacketReceiver::processPendingEvents(192.168.0.107:49653): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 00:48:33,385] - ==> [2018-10-30 00:48:33 380] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 00:48:33,426] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49658): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 00:48:33,427] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 00:48:33,428] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 00:48:33,429] - onLoginAppShutDown()
  INFO root [2018-10-30 00:48:33,429] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 00:48:33,429] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:48:33,430] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:48:33,495] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 00:48:33,495] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 00:48:34,542] - 
  INFO root [2018-10-30 00:48:34,543] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 00:48:34,543] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 00:48:34,543] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 00:48:34,543] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 00:48:34,546] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 00:48:34,546] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 00:48:34,547] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49759 )
  INFO root [2018-10-30 00:48:34,547] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49759, SOMAXCONN=128.
  INFO root [2018-10-30 00:48:34,548] - server-configs:
  INFO root [2018-10-30 00:48:34,548] - 	internalAddr : 192.168.0.107:49759
  INFO root [2018-10-30 00:48:34,548] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 00:48:34,548] - 	externalCustomAddr : 171.88.53.16
  INFO root [2018-10-30 00:48:34,548] - 	componentID : 9000
  WARN root [2018-10-30 00:48:35,038] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20643, errorno=10048
  INFO root [2018-10-30 00:48:35,041] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 17827. PID: 8096 ----
  INFO root [2018-10-30 00:48:35,042] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 00:48:35,042] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 00:48:35,042] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 00:48:35,164] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:48:35,165] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:48:35,165] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:48:35,168] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:48:35,168] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:48:35,168] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:48:35,169] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:48:35,196] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:48:35,223] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 00:48:35,223] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 00:48:35,225] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 00:48:35,225] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 00:48:35,493] - ---- loginapp is running ----
 DEBUG root [2018-10-30 00:48:35,493] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 00:48:42,585] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 00:48:42,613] - Components::findComponents: found logger, addr:192.168.0.107:49755
  INFO root [2018-10-30 00:48:42,614] - Components::addComponent: reset orderLog, uid=17827!
  INFO root [2018-10-30 00:48:42,614] - Components::addComponent[logger], uid=17827, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:48:42,616] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 00:48:42,720] - Components::findComponents: found dbmgr, addr:192.168.0.107:49758
  INFO root [2018-10-30 00:48:42,721] - Components::addComponent: reset orderLog, uid=17827!
  INFO root [2018-10-30 00:48:42,721] - Components::addComponent[dbmgr], uid=17827, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:48:42,722] - Components::findComponents: found dbmgr, addr:192.168.0.107:49758
  WARN root [2018-10-30 00:48:43,722] - Forwarding logs to logger[192.168.0.107:49755/0/0/0]...
 ERROR root [2018-10-30 00:56:16,983] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 00:56:16,987] - The following logs sent to logger failed:
  WARN root [2018-10-30 00:56:16,988] - ==> [2018-10-30 00:56:16 982] TCPPacketReceiver::processPendingEvents(192.168.0.107:49755): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 00:56:16,988] - ==> [2018-10-30 00:56:16 983] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 00:56:17,028] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 00:56:17,029] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 00:56:17,031] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 00:56:17,033] - onLoginAppShutDown()
  INFO root [2018-10-30 00:56:17,033] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 00:56:17,034] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:56:17,034] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:56:17,042] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 00:56:17,042] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 00:56:18,110] - 
  INFO root [2018-10-30 00:56:18,110] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 00:56:18,111] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 00:56:18,111] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 00:56:18,111] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 00:56:18,113] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 00:56:18,113] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 00:56:18,114] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49829 )
  INFO root [2018-10-30 00:56:18,114] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49829, SOMAXCONN=128.
  INFO root [2018-10-30 00:56:18,114] - server-configs:
  INFO root [2018-10-30 00:56:18,115] - 	internalAddr : 192.168.0.107:49829
  INFO root [2018-10-30 00:56:18,115] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 00:56:18,115] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 00:56:18,115] - 	componentID : 9000
  WARN root [2018-10-30 00:56:18,605] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20378, errorno=10048
  INFO root [2018-10-30 00:56:18,608] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 19339. PID: 5952 ----
  INFO root [2018-10-30 00:56:18,609] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 00:56:18,609] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 00:56:18,609] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 00:56:18,731] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 00:56:18,732] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 00:56:18,732] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 00:56:18,735] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 00:56:18,735] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 00:56:18,735] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 00:56:18,735] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 00:56:18,762] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 00:56:18,788] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 00:56:18,788] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 00:56:18,790] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 00:56:18,790] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 00:56:19,057] - ---- loginapp is running ----
 DEBUG root [2018-10-30 00:56:19,057] - Components::process(): Request for the process of identity...
  WARN root [2018-10-30 00:56:22,397] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20757, errorno=10048
  INFO root [2018-10-30 00:56:26,491] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 00:56:26,574] - Components::findComponents: found logger, addr:192.168.0.107:49824
  INFO root [2018-10-30 00:56:26,575] - Components::addComponent: reset orderLog, uid=19339!
  INFO root [2018-10-30 00:56:26,576] - Components::addComponent[logger], uid=19339, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:56:26,578] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 00:56:26,679] - Components::findComponents: found dbmgr, addr:192.168.0.107:49822
  INFO root [2018-10-30 00:56:26,680] - Components::addComponent: reset orderLog, uid=19339!
  INFO root [2018-10-30 00:56:26,680] - Components::addComponent[dbmgr], uid=19339, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 00:56:26,681] - Components::findComponents: found dbmgr, addr:192.168.0.107:49822
  WARN root [2018-10-30 00:56:27,681] - Forwarding logs to logger[192.168.0.107:49824/0/0/0]...
 ERROR root [2018-10-30 01:01:04,072] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:01:04,077] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:01:04,077] - ==> [2018-10-30 01:01:04 071] TCPPacketReceiver::processPendingEvents(192.168.0.107:49824): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:01:04,077] - ==> [2018-10-30 01:01:04 072] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:01:04,120] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49822): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:01:04,120] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:01:04,124] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:01:04,125] - onLoginAppShutDown()
  INFO root [2018-10-30 01:01:04,126] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:01:04,126] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:01:04,126] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:01:04,127] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:01:04,134] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:01:04,134] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:01:05,225] - 
  INFO root [2018-10-30 01:01:05,225] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:01:05,226] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:01:05,226] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:01:05,227] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:01:05,228] - NetworkInterface::initialize(EXTERNAL): Creating on interface '192.168.0.107' (= 192.168.0.107)
  INFO root [2018-10-30 01:01:05,229] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:01:05,231] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50275 )
  INFO root [2018-10-30 01:01:05,231] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50275, SOMAXCONN=128.
  INFO root [2018-10-30 01:01:05,231] - server-configs:
  INFO root [2018-10-30 01:01:05,232] - 	internalAddr : 192.168.0.107:50275
  INFO root [2018-10-30 01:01:05,232] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 01:01:05,232] - 	externalCustomAddr : 171.88.53.16
  INFO root [2018-10-30 01:01:05,232] - 	componentID : 9000
  INFO root [2018-10-30 01:01:06,923] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20276. PID: 7980 ----
  INFO root [2018-10-30 01:01:06,923] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:01:06,923] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:01:06,924] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:01:07,046] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:01:07,046] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:01:07,047] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:01:07,050] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:01:07,050] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:01:07,050] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:01:07,050] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:01:07,076] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:01:07,103] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:01:07,103] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:01:07,105] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:01:07,105] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:01:07,385] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:01:07,385] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:01:14,505] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:01:14,550] - Components::findComponents: found logger, addr:192.168.0.107:50276
  INFO root [2018-10-30 01:01:14,551] - Components::addComponent: reset orderLog, uid=20276!
  INFO root [2018-10-30 01:01:14,551] - Components::addComponent[logger], uid=20276, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:01:14,553] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:01:14,653] - Components::findComponents: found dbmgr, addr:192.168.0.107:50277
  INFO root [2018-10-30 01:01:14,654] - Components::addComponent: reset orderLog, uid=20276!
  INFO root [2018-10-30 01:01:14,654] - Components::addComponent[dbmgr], uid=20276, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:01:14,654] - Components::findComponents: found dbmgr, addr:192.168.0.107:50277
  WARN root [2018-10-30 01:01:15,655] - Forwarding logs to logger[192.168.0.107:50276/0/0/0]...
 ERROR root [2018-10-30 01:04:06,313] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:04:06,314] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:04:06,315] - ==> [2018-10-30 01:04:06 312] TCPPacketReceiver::processPendingEvents(192.168.0.107:50276): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:04:06,315] - ==> [2018-10-30 01:04:06 313] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:04:06,360] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50277): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:04:06,361] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:04:06,364] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:04:06,366] - onLoginAppShutDown()
  INFO root [2018-10-30 01:04:06,366] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:04:06,366] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:04:06,366] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:04:06,367] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:04:06,375] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:04:06,375] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:04:07,455] - 
  INFO root [2018-10-30 01:04:07,455] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:04:07,456] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:04:07,456] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:04:07,456] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:04:07,457] - NetworkInterface::initialize(EXTERNAL): Creating on interface '192.168.0.107' (= 192.168.0.107)
  INFO root [2018-10-30 01:04:07,457] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:04:07,458] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50332 )
  INFO root [2018-10-30 01:04:07,459] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50332, SOMAXCONN=128.
  INFO root [2018-10-30 01:04:07,459] - server-configs:
  INFO root [2018-10-30 01:04:07,459] - 	internalAddr : 192.168.0.107:50332
  INFO root [2018-10-30 01:04:07,459] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 01:04:07,459] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 01:04:07,459] - 	componentID : 9000
  WARN root [2018-10-30 01:04:07,950] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20733, errorno=10048
  INFO root [2018-10-30 01:04:07,956] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20874. PID: 9580 ----
  INFO root [2018-10-30 01:04:07,957] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:04:07,957] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:04:07,958] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:04:08,084] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:04:08,084] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:04:08,085] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:04:08,088] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:04:08,088] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:04:08,088] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:04:08,088] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:04:08,115] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:04:08,143] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:04:08,143] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:04:08,144] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:04:08,145] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:04:08,411] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:04:08,411] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:04:15,526] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:04:15,544] - Components::findComponents: found logger, addr:192.168.0.107:50327
  INFO root [2018-10-30 01:04:15,544] - Components::addComponent: reset orderLog, uid=20874!
  INFO root [2018-10-30 01:04:15,545] - Components::addComponent[logger], uid=20874, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:04:15,547] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:04:15,649] - Components::findComponents: found dbmgr, addr:192.168.0.107:50331
  INFO root [2018-10-30 01:04:15,649] - Components::addComponent: reset orderLog, uid=20874!
  INFO root [2018-10-30 01:04:15,649] - Components::addComponent[dbmgr], uid=20874, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:04:15,649] - Components::findComponents: found dbmgr, addr:192.168.0.107:50331
  WARN root [2018-10-30 01:04:16,650] - Forwarding logs to logger[192.168.0.107:50327/0/0/0]...
 ERROR root [2018-10-30 01:06:59,831] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:06:59,836] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:06:59,837] - ==> [2018-10-30 01:06:59 830] TCPPacketReceiver::processPendingEvents(192.168.0.107:50327): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:06:59,837] - ==> [2018-10-30 01:06:59 831] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:06:59,878] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50331): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:06:59,878] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:06:59,880] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:06:59,882] - onLoginAppShutDown()
  INFO root [2018-10-30 01:06:59,882] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:06:59,882] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:06:59,883] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:06:59,891] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:06:59,891] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:07:00,970] - 
  INFO root [2018-10-30 01:07:00,970] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:07:00,971] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:07:00,971] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:07:00,971] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:07:00,972] - NetworkInterface::initialize(EXTERNAL): Creating on interface '192.168.0.107' (= 192.168.0.107)
  INFO root [2018-10-30 01:07:00,972] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:07:00,973] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50409 )
  INFO root [2018-10-30 01:07:00,973] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50409, SOMAXCONN=128.
  INFO root [2018-10-30 01:07:00,973] - server-configs:
  INFO root [2018-10-30 01:07:00,973] - 	internalAddr : 192.168.0.107:50409
  INFO root [2018-10-30 01:07:00,973] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 01:07:00,973] - 	externalCustomAddr : 171.88.53.16
  INFO root [2018-10-30 01:07:00,974] - 	componentID : 9000
  INFO root [2018-10-30 01:07:02,659] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 21439. PID: 10172 ----
  INFO root [2018-10-30 01:07:02,660] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:07:02,660] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:07:02,660] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:07:02,782] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:07:02,782] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:07:02,782] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:07:02,785] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:07:02,786] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:07:02,786] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:07:02,786] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:07:02,813] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:07:02,841] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:07:02,841] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:07:02,843] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:07:02,843] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:07:03,118] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:07:03,118] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:07:10,224] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:07:10,263] - Components::findComponents: found logger, addr:192.168.0.107:50405
  INFO root [2018-10-30 01:07:10,264] - Components::addComponent: reset orderLog, uid=21439!
  INFO root [2018-10-30 01:07:10,265] - Components::addComponent[logger], uid=21439, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:07:10,267] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:07:10,368] - Components::findComponents: found dbmgr, addr:192.168.0.107:50403
  INFO root [2018-10-30 01:07:10,369] - Components::addComponent: reset orderLog, uid=21439!
  INFO root [2018-10-30 01:07:10,369] - Components::addComponent[dbmgr], uid=21439, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:07:10,370] - Components::findComponents: found dbmgr, addr:192.168.0.107:50403
  WARN root [2018-10-30 01:07:11,370] - Forwarding logs to logger[192.168.0.107:50405/0/0/0]...
 ERROR root [2018-10-30 01:07:38,144] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:07:38,150] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:07:38,150] - ==> [2018-10-30 01:07:38 143] TCPPacketReceiver::processPendingEvents(192.168.0.107:50405): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:07:38,150] - ==> [2018-10-30 01:07:38 144] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:07:38,193] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50403): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:07:38,194] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:07:38,194] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:07:38,197] - onLoginAppShutDown()
  INFO root [2018-10-30 01:07:38,197] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:07:38,197] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:07:38,197] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:07:38,198] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:07:38,198] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:07:38,206] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:07:38,207] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:07:39,290] - 
  INFO root [2018-10-30 01:07:39,291] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:07:39,291] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:07:39,292] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:07:39,292] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:07:39,293] - NetworkInterface::initialize(EXTERNAL): Creating on interface '171.88.53.16' (= 171.88.53.16)
 ERROR root [2018-10-30 01:07:39,293] - NetworkInterface::initialize(EXTERNAL): Couldn't bind the socket to 171.88.53.16:20013 (errorno=10049)
  INFO root [2018-10-30 01:07:39,293] - assertion failed: extEndpoint_.good() && "Channel::EXTERNAL: no available port, " "please check for kbengine[_defs].xml!\n", file e:\kbengine\kbe\src\lib\network\network_interface.cpp, line 53, at: KBEngine::Network::NetworkInterface::NetworkInterface
  INFO root [2018-10-30 01:08:12,849] - 
  INFO root [2018-10-30 01:08:12,849] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:08:12,850] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:08:12,850] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:08:12,850] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:08:12,851] - NetworkInterface::initialize(EXTERNAL): Creating on interface '192.168.0.1' (= 192.168.0.1)
 ERROR root [2018-10-30 01:08:12,851] - NetworkInterface::initialize(EXTERNAL): Couldn't bind the socket to 192.168.0.1:20013 (errorno=10049)
  INFO root [2018-10-30 01:08:12,851] - assertion failed: extEndpoint_.good() && "Channel::EXTERNAL: no available port, " "please check for kbengine[_defs].xml!\n", file e:\kbengine\kbe\src\lib\network\network_interface.cpp, line 53, at: KBEngine::Network::NetworkInterface::NetworkInterface
  INFO root [2018-10-30 01:16:40,664] - 
  INFO root [2018-10-30 01:16:40,665] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:16:40,666] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:16:40,666] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:16:40,666] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:16:40,669] - NetworkInterface::initialize(EXTERNAL): Creating on interface '127.0.0.1' (= 127.0.0.1)
  INFO root [2018-10-30 01:16:40,670] - NetworkInterface::initialize(EXTERNAL): address 127.0.0.1:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:16:40,675] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52661 )
  INFO root [2018-10-30 01:16:40,675] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52661, SOMAXCONN=128.
  INFO root [2018-10-30 01:16:40,675] - server-configs:
  INFO root [2018-10-30 01:16:40,675] - 	internalAddr : 192.168.0.107:52661
  INFO root [2018-10-30 01:16:40,675] - 	externalAddr : 127.0.0.1:20013
  INFO root [2018-10-30 01:16:40,675] - 	externalCustomAddr : 171.88.53.16
  INFO root [2018-10-30 01:16:40,675] - 	componentID : 9000
  WARN root [2018-10-30 01:16:41,193] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20114, errorno=10048
  INFO root [2018-10-30 01:16:41,197] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23333. PID: 7644 ----
  INFO root [2018-10-30 01:16:41,197] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:16:41,197] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:16:41,198] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:16:41,322] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:16:41,323] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:16:41,323] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:16:41,326] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:16:41,326] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:16:41,326] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:16:41,327] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:16:41,354] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:16:41,384] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:16:41,384] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:16:41,386] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:16:41,386] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:16:41,653] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:16:41,653] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:16:48,747] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:16:48,769] - Components::findComponents: found logger, addr:192.168.0.107:52658
  INFO root [2018-10-30 01:16:48,769] - Components::addComponent: reset orderLog, uid=23333!
  INFO root [2018-10-30 01:16:48,769] - Components::addComponent[logger], uid=23333, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:16:48,770] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:16:48,876] - Components::findComponents: found dbmgr, addr:192.168.0.107:52656
  INFO root [2018-10-30 01:16:48,876] - Components::addComponent: reset orderLog, uid=23333!
  INFO root [2018-10-30 01:16:48,877] - Components::addComponent[dbmgr], uid=23333, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:16:48,877] - Components::findComponents: found dbmgr, addr:192.168.0.107:52656
  WARN root [2018-10-30 01:16:49,878] - Forwarding logs to logger[192.168.0.107:52658/0/0/0]...
 ERROR root [2018-10-30 01:17:55,034] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:17:55,039] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:17:55,040] - ==> [2018-10-30 01:17:55 034] TCPPacketReceiver::processPendingEvents(192.168.0.107:52658): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:17:55,040] - ==> [2018-10-30 01:17:55 035] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:17:55,084] - TCPPacketReceiver::processPendingEvents(192.168.0.107:52656): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:17:55,085] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:17:55,089] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:17:55,090] - onLoginAppShutDown()
  INFO root [2018-10-30 01:17:55,090] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:17:55,090] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:17:55,091] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:17:55,099] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:17:55,099] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:17:56,218] - 
  INFO root [2018-10-30 01:17:56,218] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:17:56,219] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:17:56,219] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:17:56,219] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:17:56,221] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 01:17:56,221] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:17:56,222] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52710 )
  INFO root [2018-10-30 01:17:56,222] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52710, SOMAXCONN=128.
  INFO root [2018-10-30 01:17:56,222] - server-configs:
  INFO root [2018-10-30 01:17:56,222] - 	internalAddr : 192.168.0.107:52710
  INFO root [2018-10-30 01:17:56,222] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 01:17:56,222] - 	externalCustomAddr : 192.168.0.107
  INFO root [2018-10-30 01:17:56,223] - 	componentID : 9000
  INFO root [2018-10-30 01:17:57,900] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23578. PID: 10272 ----
  INFO root [2018-10-30 01:17:57,901] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:17:57,901] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:17:57,901] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:17:58,024] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:17:58,024] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:17:58,025] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:17:58,028] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:17:58,028] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:17:58,028] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:17:58,028] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:17:58,056] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:17:58,090] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:17:58,090] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:17:58,092] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:17:58,092] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:17:58,435] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:17:58,435] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:18:05,552] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:18:05,635] - Components::findComponents: found logger, addr:192.168.0.107:52704
  INFO root [2018-10-30 01:18:05,636] - Components::addComponent: reset orderLog, uid=23578!
  INFO root [2018-10-30 01:18:05,636] - Components::addComponent[logger], uid=23578, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:18:05,638] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:18:05,738] - Components::findComponents: found dbmgr, addr:192.168.0.107:52705
  INFO root [2018-10-30 01:18:05,738] - Components::addComponent: reset orderLog, uid=23578!
  INFO root [2018-10-30 01:18:05,738] - Components::addComponent[dbmgr], uid=23578, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:18:05,739] - Components::findComponents: found dbmgr, addr:192.168.0.107:52705
  WARN root [2018-10-30 01:18:06,739] - Forwarding logs to logger[192.168.0.107:52704/0/0/0]...
 ERROR root [2018-10-30 01:18:27,731] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:18:27,736] - The following logs sent to logger failed:
  WARN root [2018-10-30 01:18:27,737] - ==> [2018-10-30 01:18:27 730] TCPPacketReceiver::processPendingEvents(192.168.0.107:52704): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:18:27,737] - ==> [2018-10-30 01:18:27 731] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-30 01:18:27,779] - TCPPacketReceiver::processPendingEvents(192.168.0.107:52705): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-30 01:18:27,779] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-30 01:18:27,783] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-30 01:18:27,785] - onLoginAppShutDown()
  INFO root [2018-10-30 01:18:27,785] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-30 01:18:27,785] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-30 01:18:27,785] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:18:27,785] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:18:27,785] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:18:27,785] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:18:27,785] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:18:27,786] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:18:27,786] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:18:27,786] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:18:27,793] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-30 01:18:27,793] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-30 01:18:28,879] - 
  INFO root [2018-10-30 01:18:28,879] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-30 01:18:28,880] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-30 01:18:28,880] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-30 01:18:28,880] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-30 01:18:28,884] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-30 01:18:28,884] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-30 01:18:28,885] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52750 )
  INFO root [2018-10-30 01:18:28,885] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52750, SOMAXCONN=128.
  INFO root [2018-10-30 01:18:28,885] - server-configs:
  INFO root [2018-10-30 01:18:28,885] - 	internalAddr : 192.168.0.107:52750
  INFO root [2018-10-30 01:18:28,886] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-30 01:18:28,886] - 	componentID : 9000
  WARN root [2018-10-30 01:18:29,381] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20727, errorno=10048
  INFO root [2018-10-30 01:18:29,386] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23686. PID: 10732 ----
  INFO root [2018-10-30 01:18:29,386] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-30 01:18:29,386] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-30 01:18:29,387] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-30 01:18:29,509] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-30 01:18:29,509] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-30 01:18:29,509] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-30 01:18:29,512] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-30 01:18:29,512] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-30 01:18:29,512] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-30 01:18:29,513] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-30 01:18:29,541] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-30 01:18:29,578] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-30 01:18:29,578] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-30 01:18:29,581] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-30 01:18:29,581] - TelnetServer server is running on port 31000
  INFO root [2018-10-30 01:18:29,851] - ---- loginapp is running ----
 DEBUG root [2018-10-30 01:18:29,851] - Components::process(): Request for the process of identity...
  INFO root [2018-10-30 01:18:36,962] - Components::findComponents: find logger(1)...
  INFO root [2018-10-30 01:18:37,020] - Components::findComponents: found logger, addr:192.168.0.107:52743
  INFO root [2018-10-30 01:18:37,021] - Components::addComponent: reset orderLog, uid=23686!
  INFO root [2018-10-30 01:18:37,022] - Components::addComponent[logger], uid=23686, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:18:37,024] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-30 01:18:37,128] - Components::findComponents: found dbmgr, addr:192.168.0.107:52745
  INFO root [2018-10-30 01:18:37,129] - Components::addComponent: reset orderLog, uid=23686!
  INFO root [2018-10-30 01:18:37,129] - Components::addComponent[dbmgr], uid=23686, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-30 01:18:37,130] - Components::findComponents: found dbmgr, addr:192.168.0.107:52745
  WARN root [2018-10-30 01:18:38,130] - Forwarding logs to logger[192.168.0.107:52743/0/0/0]...
